import { pronunciations } from "./pronunciations.ts";
import { expandedWords } from "./vocabulary-expanded.ts";

export type Word = {
  ipa: string;
  exampleIpa: string;
  id: string;
  word: string;
  pos: string;
  meaning: string;
  category: string;
  example: string;
  translation: string;
  phrase: string;
  question: string;
  explanation: string;
  quizType?: "cloze" | "meaning";
};
const rows = [
  [
    "職場與人事",
    "applicant",
    "n.",
    "應徵者",
    "Each applicant must submit a résumé.",
    "每位應徵者都必須提交履歷。",
    "a qualified applicant",
    "Each _____ must submit a résumé.",
    "applicant 指應徵職位的人；此處 each 後接單數名詞。",
  ],
  [
    "職場與人事",
    "recruit",
    "v.",
    "招募",
    "The company plans to recruit ten engineers.",
    "公司計畫招募十位工程師。",
    "recruit new employees",
    "The company plans to _____ ten engineers.",
    "recruit 表示招募人員，後面可接職位或人員。",
  ],
  [
    "職場與人事",
    "qualification",
    "n.",
    "資格；資歷",
    "Experience is an essential qualification for this position.",
    "經驗是這個職位的必要資格。",
    "an essential qualification",
    "Experience is an essential _____ for this position.",
    "qualification 指符合工作要求的資格或條件。",
  ],
  [
    "職場與人事",
    "candidate",
    "n.",
    "候選人；應徵者",
    "The manager interviewed the candidate yesterday.",
    "經理昨天面試了那位應徵者。",
    "a suitable candidate",
    "The manager interviewed the _____ yesterday.",
    "candidate 指職位或選舉的候選人。",
  ],
  [
    "職場與人事",
    "supervisor",
    "n.",
    "主管",
    "Please ask your supervisor for approval.",
    "請向你的主管申請核准。",
    "an immediate supervisor",
    "Please ask your _____ for approval.",
    "supervisor 是負責監督工作的人，也就是主管。",
  ],
  [
    "職場與人事",
    "promotion",
    "n.",
    "升遷；促銷",
    "She received a promotion after two years.",
    "她在兩年後獲得升遷。",
    "receive a promotion",
    "She received a _____ after two years.",
    "在職場語境中，receive a promotion 表示獲得升遷。",
  ],
  [
    "職場與人事",
    "resign",
    "v.",
    "辭職",
    "He decided to resign from his position.",
    "他決定辭去職位。",
    "resign from a position",
    "He decided to _____ from his position.",
    "resign from 表示辭去某個職位。",
  ],
  [
    "職場與人事",
    "salary",
    "n.",
    "薪資",
    "The position offers a competitive salary.",
    "這個職位提供具競爭力的薪資。",
    "a competitive salary",
    "The position offers a competitive _____.",
    "salary 通常指固定的薪資。",
  ],
  [
    "職場與人事",
    "orientation",
    "n.",
    "新人訓練；介紹會",
    "New employees will attend orientation on Monday.",
    "新員工將在星期一參加新人訓練。",
    "employee orientation",
    "New employees will attend _____ on Monday.",
    "orientation 在此指協助新員工熟悉公司的活動。",
  ],
  [
    "職場與人事",
    "colleague",
    "n.",
    "同事",
    "My colleague helped me prepare the report.",
    "我的同事幫我準備報告。",
    "a former colleague",
    "My _____ helped me prepare the report.",
    "colleague 指一起工作的人。",
  ],
  [
    "職場與人事",
    "evaluate",
    "v.",
    "評估",
    "We evaluate employee performance every year.",
    "我們每年評估員工表現。",
    "evaluate performance",
    "We _____ employee performance every year.",
    "evaluate 表示評估品質、能力或表現。",
  ],
  [
    "職場與人事",
    "attend",
    "v.",
    "出席；參加",
    "All staff members should attend the workshop.",
    "所有員工都應參加研習會。",
    "attend a workshop",
    "All staff members should _____ the workshop.",
    "attend 可直接接受詞，不必加 to。",
  ],
  [
    "會議與辦公",
    "agenda",
    "n.",
    "議程",
    "Please review the agenda before the meeting.",
    "請在會議前查看議程。",
    "review the agenda",
    "Please review the _____ before the meeting.",
    "agenda 是會議中預計討論的事項。",
  ],
  [
    "會議與辦公",
    "postpone",
    "v.",
    "延期",
    "We need to postpone the meeting until Friday.",
    "我們需要把會議延到星期五。",
    "postpone a meeting",
    "We need to _____ the meeting until Friday.",
    "postpone 表示把活動延後，until 接延後到的時間。",
  ],
  [
    "會議與辦公",
    "deadline",
    "n.",
    "截止期限",
    "The deadline for applications is June 30.",
    "申請截止日期是六月三十日。",
    "meet a deadline",
    "The _____ for applications is June 30.",
    "deadline 指必須完成某件事的最後期限。",
  ],
  [
    "會議與辦公",
    "confirm",
    "v.",
    "確認",
    "Please confirm your attendance by email.",
    "請透過電子郵件確認是否出席。",
    "confirm attendance",
    "Please _____ your attendance by email.",
    "confirm 表示確認資訊或安排。",
  ],
  [
    "會議與辦公",
    "annual",
    "adj.",
    "每年的",
    "Our annual conference takes place in May.",
    "我們的年度會議在五月舉行。",
    "an annual conference",
    "Our _____ conference takes place in May.",
    "annual 是形容詞，表示一年一次的。",
  ],
  [
    "會議與辦公",
    "notify",
    "v.",
    "通知",
    "We will notify you of any changes.",
    "如有任何變更，我們會通知你。",
    "notify someone of something",
    "We will _____ you of any changes.",
    "notify someone of something 表示把某事通知某人。",
  ],
  [
    "會議與辦公",
    "submit",
    "v.",
    "提交",
    "Please submit your report by noon.",
    "請在中午前提交報告。",
    "submit a report",
    "Please _____ your report by noon.",
    "submit 指正式提交文件或申請。",
  ],
  [
    "會議與辦公",
    "attach",
    "v.",
    "附上",
    "Remember to attach the file to your email.",
    "記得在電子郵件中附上檔案。",
    "attach a file",
    "Remember to _____ the file to your email.",
    "attach A to B 表示把 A 附加到 B。",
  ],
  [
    "會議與辦公",
    "available",
    "adj.",
    "可取得的；有空的",
    "The meeting room is available this afternoon.",
    "會議室今天下午可以使用。",
    "be available",
    "The meeting room is _____ this afternoon.",
    "available 在此表示可以使用的。",
  ],
  [
    "會議與辦公",
    "arrange",
    "v.",
    "安排",
    "Our assistant will arrange transportation.",
    "我們的助理會安排交通。",
    "arrange transportation",
    "Our assistant will _____ transportation.",
    "arrange 表示安排活動、交通或其他事務。",
  ],
  [
    "會議與辦公",
    "equipment",
    "n.",
    "設備",
    "The office needs new equipment.",
    "辦公室需要新設備。",
    "office equipment",
    "The office needs new _____.",
    "equipment 是不可數名詞，通常不加 s。",
  ],
  [
    "會議與辦公",
    "procedure",
    "n.",
    "程序；步驟",
    "Please follow the safety procedure.",
    "請遵循安全程序。",
    "follow a procedure",
    "Please follow the safety _____.",
    "procedure 指完成某件事所需遵循的步驟。",
  ],
  [
    "差旅與住宿",
    "reservation",
    "n.",
    "預約；訂位",
    "I would like to make a reservation for two.",
    "我想預訂兩位的座位。",
    "make a reservation",
    "I would like to make a _____ for two.",
    "make a reservation 是預約、訂位的常見搭配。",
  ],
  [
    "差旅與住宿",
    "itinerary",
    "n.",
    "行程表",
    "Your travel itinerary is attached.",
    "你的旅行行程表已附上。",
    "a travel itinerary",
    "Your travel _____ is attached.",
    "itinerary 是列出旅程安排的行程表。",
  ],
  [
    "差旅與住宿",
    "departure",
    "n.",
    "出發；離境",
    "Please arrive one hour before departure.",
    "請在出發前一小時抵達。",
    "departure time",
    "Please arrive one hour before _____.",
    "departure 指離開或出發，與 arrival 相對。",
  ],
  [
    "差旅與住宿",
    "destination",
    "n.",
    "目的地",
    "Paris is our final destination.",
    "巴黎是我們的最終目的地。",
    "final destination",
    "Paris is our final _____.",
    "destination 是旅程預計到達的地方。",
  ],
  [
    "差旅與住宿",
    "accommodation",
    "n.",
    "住宿",
    "The company will pay for your accommodation.",
    "公司將支付你的住宿費用。",
    "book accommodation",
    "The company will pay for your _____.",
    "accommodation 在旅行語境中指住宿。",
  ],
  [
    "差旅與住宿",
    "complimentary",
    "adj.",
    "免費招待的",
    "The hotel offers complimentary breakfast.",
    "這家飯店提供免費早餐。",
    "complimentary breakfast",
    "The hotel offers _____ breakfast.",
    "complimentary 在此表示免費提供給客人的。",
  ],
  [
    "差旅與住宿",
    "luggage",
    "n.",
    "行李",
    "Please do not leave your luggage unattended.",
    "請勿讓你的行李無人看管。",
    "carry-on luggage",
    "Please do not leave your _____ unattended.",
    "luggage 是不可數名詞，指旅行行李。",
  ],
  [
    "差旅與住宿",
    "delay",
    "n.",
    "延誤",
    "There was a two-hour delay because of the storm.",
    "因為暴風雨而延誤了兩小時。",
    "a flight delay",
    "There was a two-hour _____ because of the storm.",
    "delay 作名詞時表示延誤的情況。",
  ],
  [
    "差旅與住宿",
    "board",
    "v.",
    "登上（交通工具）",
    "Passengers may board the plane now.",
    "旅客現在可以登機。",
    "board a plane",
    "Passengers may _____ the plane now.",
    "board 作動詞時可指登上飛機、船或列車。",
  ],
  [
    "差旅與住宿",
    "shuttle",
    "n.",
    "接駁車",
    "A free shuttle runs between the hotel and airport.",
    "飯店與機場之間有免費接駁車。",
    "an airport shuttle",
    "A free _____ runs between the hotel and airport.",
    "shuttle 指在固定地點之間往返的接駁交通工具。",
  ],
  [
    "差旅與住宿",
    "vacancy",
    "n.",
    "空房；職缺",
    "The hotel has no vacancy tonight.",
    "這家飯店今晚沒有空房。",
    "no vacancy",
    "The hotel has no _____ tonight.",
    "vacancy 在飯店情境中表示空房。",
  ],
  [
    "差旅與住宿",
    "valid",
    "adj.",
    "有效的",
    "You must present a valid passport.",
    "你必須出示有效護照。",
    "a valid passport",
    "You must present a _____ passport.",
    "valid 表示仍有效、可被接受的。",
  ],
  [
    "採購與物流",
    "supplier",
    "n.",
    "供應商",
    "We are looking for a reliable supplier.",
    "我們正在尋找可靠的供應商。",
    "a reliable supplier",
    "We are looking for a reliable _____.",
    "supplier 是提供商品或原料的人或公司。",
  ],
  [
    "採購與物流",
    "shipment",
    "n.",
    "貨件；出貨",
    "The shipment will arrive tomorrow.",
    "貨件將於明天抵達。",
    "track a shipment",
    "The _____ will arrive tomorrow.",
    "shipment 可指一批運送的貨物。",
  ],
  [
    "採購與物流",
    "inventory",
    "n.",
    "庫存",
    "We check our inventory every month.",
    "我們每個月檢查庫存。",
    "check inventory",
    "We check our _____ every month.",
    "inventory 指商家持有的存貨。",
  ],
  [
    "採購與物流",
    "purchase",
    "v.",
    "購買",
    "You can purchase tickets online.",
    "你可以在線上購票。",
    "purchase tickets",
    "You can _____ tickets online.",
    "purchase 是 buy 的較正式說法。",
  ],
  [
    "採購與物流",
    "warehouse",
    "n.",
    "倉庫",
    "The goods are stored in a warehouse.",
    "貨物存放在倉庫中。",
    "a storage warehouse",
    "The goods are stored in a _____.",
    "warehouse 是大量存放貨品的建築。",
  ],
  [
    "採購與物流",
    "quantity",
    "n.",
    "數量",
    "Please specify the quantity you need.",
    "請註明你需要的數量。",
    "a large quantity",
    "Please specify the _____ you need.",
    "quantity 指某物的數量。",
  ],
  [
    "採購與物流",
    "deliver",
    "v.",
    "運送；交付",
    "We deliver orders within three business days.",
    "我們會在三個工作天內送達訂單。",
    "deliver an order",
    "We _____ orders within three business days.",
    "deliver 表示把貨品送到指定地點。",
  ],
  [
    "採購與物流",
    "receipt",
    "n.",
    "收據",
    "Please keep your receipt for a refund.",
    "請保留收據以便退款。",
    "keep a receipt",
    "Please keep your _____ for a refund.",
    "receipt 是付款後取得的憑證。",
  ],
  [
    "採購與物流",
    "defective",
    "adj.",
    "有瑕疵的",
    "We will replace any defective products.",
    "我們會更換任何有瑕疵的產品。",
    "a defective product",
    "We will replace any _____ products.",
    "defective 表示有缺陷、無法正常運作的。",
  ],
  [
    "採購與物流",
    "warranty",
    "n.",
    "保固",
    "This printer comes with a one-year warranty.",
    "這台印表機附有一年保固。",
    "a one-year warranty",
    "This printer comes with a one-year _____.",
    "warranty 是產品維修或更換的保證。",
  ],
  [
    "採購與物流",
    "refund",
    "n.",
    "退款",
    "You may request a full refund within seven days.",
    "你可以在七天內要求全額退款。",
    "a full refund",
    "You may request a full _____ within seven days.",
    "refund 指退還已支付的款項。",
  ],
  [
    "採購與物流",
    "distribute",
    "v.",
    "分發；配送",
    "Please distribute these brochures to visitors.",
    "請把這些手冊分發給訪客。",
    "distribute brochures",
    "Please _____ these brochures to visitors.",
    "distribute A to B 表示把 A 分發給 B。",
  ],
  [
    "財務與商務",
    "reimburse",
    "v.",
    "報銷；償還",
    "The company will reimburse you for travel expenses.",
    "公司會報銷你的差旅費。",
    "reimburse someone for expenses",
    "The company will _____ you for travel expenses.",
    "reimburse someone for something 表示為某項支出補償某人。",
  ],
  [
    "財務與商務",
    "invoice",
    "n.",
    "請款單；發票",
    "Please pay the invoice within thirty days.",
    "請在三十天內支付這張請款單。",
    "pay an invoice",
    "Please pay the _____ within thirty days.",
    "invoice 是列出商品或服務費用的請款文件。",
  ],
  [
    "財務與商務",
    "budget",
    "n.",
    "預算",
    "The project must stay within the budget.",
    "這個專案必須控制在預算內。",
    "within the budget",
    "The project must stay within the _____.",
    "budget 指為特定用途規劃的金額。",
  ],
  [
    "財務與商務",
    "revenue",
    "n.",
    "營收",
    "The company reported higher revenue this quarter.",
    "公司公布本季營收增加。",
    "annual revenue",
    "The company reported higher _____ this quarter.",
    "revenue 指營業收入，尚未扣除成本。",
  ],
  [
    "財務與商務",
    "expense",
    "n.",
    "費用；支出",
    "Transportation is a major expense for the business.",
    "交通是這家企業的一項主要支出。",
    "a business expense",
    "Transportation is a major _____ for the business.",
    "expense 指花費的款項或成本。",
  ],
  [
    "財務與商務",
    "estimate",
    "n.",
    "估價；估計",
    "Could you provide an estimate for the repairs?",
    "你能提供維修估價嗎？",
    "provide an estimate",
    "Could you provide an _____ for the repairs?",
    "estimate 作名詞時可指預估費用。",
  ],
  [
    "財務與商務",
    "contract",
    "n.",
    "合約",
    "Both parties signed the contract.",
    "雙方都簽署了合約。",
    "sign a contract",
    "Both parties signed the _____.",
    "contract 是雙方或多方訂立的合約。",
  ],
  [
    "財務與商務",
    "negotiate",
    "v.",
    "協商；談判",
    "We hope to negotiate a better price.",
    "我們希望協商出更好的價格。",
    "negotiate a price",
    "We hope to _____ a better price.",
    "negotiate 表示透過討論達成協議。",
  ],
  [
    "財務與商務",
    "discount",
    "n.",
    "折扣",
    "Members receive a ten-percent discount.",
    "會員可享百分之十的折扣。",
    "receive a discount",
    "Members receive a ten-percent _____.",
    "discount 是從原價減去的金額或比例。",
  ],
  [
    "財務與商務",
    "deposit",
    "n.",
    "訂金；存款",
    "A deposit is required to reserve the room.",
    "預訂房間需要支付訂金。",
    "pay a deposit",
    "A _____ is required to reserve the room.",
    "deposit 在此指預訂時先支付的一部分款項。",
  ],
  [
    "財務與商務",
    "profit",
    "n.",
    "利潤",
    "The store made a profit last year.",
    "這家商店去年有獲利。",
    "make a profit",
    "The store made a _____ last year.",
    "profit 是收入扣除成本後的利潤。",
  ],
  [
    "財務與商務",
    "approve",
    "v.",
    "核准",
    "The director must approve the request.",
    "主管必須核准這項申請。",
    "approve a request",
    "The director must _____ the request.",
    "approve 在此表示正式同意或核准。",
  ],
  [
    "服務與設施",
    "maintenance",
    "n.",
    "維護；保養",
    "The elevator is closed for maintenance.",
    "電梯因維護而暫停使用。",
    "scheduled maintenance",
    "The elevator is closed for _____.",
    "maintenance 指讓設備保持正常的保養工作。",
  ],
  [
    "服務與設施",
    "renovation",
    "n.",
    "整修",
    "The restaurant is undergoing renovation.",
    "餐廳正在整修。",
    "undergo renovation",
    "The restaurant is undergoing _____.",
    "renovation 指修復或改善建築物。",
  ],
  [
    "服務與設施",
    "inquiry",
    "n.",
    "詢問",
    "Thank you for your inquiry about our services.",
    "感謝你詢問我們的服務。",
    "a customer inquiry",
    "Thank you for your _____ about our services.",
    "inquiry 指詢問或索取資訊。",
  ],
  [
    "服務與設施",
    "resolve",
    "v.",
    "解決",
    "We will resolve the issue as soon as possible.",
    "我們會盡快解決這個問題。",
    "resolve an issue",
    "We will _____ the issue as soon as possible.",
    "resolve 在此表示找到問題的解決方式。",
  ],
  [
    "服務與設施",
    "convenient",
    "adj.",
    "方便的",
    "The new location is convenient for commuters.",
    "新地點對通勤者很方便。",
    "a convenient location",
    "The new location is _____ for commuters.",
    "convenient 表示符合需求且省時省力的。",
  ],
  [
    "服務與設施",
    "facility",
    "n.",
    "設施",
    "The new facility includes a gym.",
    "新設施包含一間健身房。",
    "a sports facility",
    "The new _____ includes a gym.",
    "facility 指為特定目的建造的場所或設施。",
  ],
  [
    "服務與設施",
    "inspect",
    "v.",
    "檢查",
    "A technician will inspect the equipment today.",
    "技師今天將檢查設備。",
    "inspect equipment",
    "A technician will _____ the equipment today.",
    "inspect 指仔細檢查狀況或品質。",
  ],
  [
    "服務與設施",
    "replace",
    "v.",
    "更換；取代",
    "We need to replace the broken printer.",
    "我們需要更換壞掉的印表機。",
    "replace a printer",
    "We need to _____ the broken printer.",
    "replace 表示用新的物品取代舊的。",
  ],
  [
    "服務與設施",
    "accessible",
    "adj.",
    "可進入的；無障礙的",
    "The building is accessible to wheelchair users.",
    "輪椅使用者可以進入這棟建築。",
    "accessible to everyone",
    "The building is _____ to wheelchair users.",
    "accessible to 表示某人可以使用或進入。",
  ],
  [
    "服務與設施",
    "apologize",
    "v.",
    "道歉",
    "We apologize for the inconvenience.",
    "對於造成的不便，我們深感抱歉。",
    "apologize for something",
    "We _____ for the inconvenience.",
    "apologize for 表示為某件事道歉。",
  ],
  [
    "服務與設施",
    "assistance",
    "n.",
    "協助",
    "Please contact us if you need assistance.",
    "如果你需要協助，請聯絡我們。",
    "request assistance",
    "Please contact us if you need _____.",
    "assistance 是 help 的較正式說法，為不可數名詞。",
  ],
  [
    "服務與設施",
    "policy",
    "n.",
    "政策；規定",
    "Please read our return policy before purchasing.",
    "購買前請閱讀我們的退貨規定。",
    "a return policy",
    "Please read our return _____ before purchasing.",
    "policy 是組織採用的規定或方針。",
  ],
];
const starterWords: Word[] = rows.map(
  ([
    category,
    word,
    pos,
    meaning,
    example,
    translation,
    phrase,
    question,
    explanation,
  ]) => ({
    id: word,
    ...pronunciations[word],
    category,
    word,
    pos,
    meaning,
    example,
    translation,
    phrase,
    question,
    explanation,
  }),
);
// Keep the original IDs and learning order, then alternate new topic packs.
const additionsByCategory = new Map<string, Word[]>();
for (const word of expandedWords) {
  const group = additionsByCategory.get(word.category) ?? [];
  group.push(word);
  additionsByCategory.set(word.category, group);
}
const additions = Array.from({ length: 46 }, (_, index) =>
  [...additionsByCategory.values()].map((group) => group[index]),
).flat();
export const words: Word[] = [...starterWords, ...additions];
export const categories = [...new Set(words.map((w) => w.category))];
